import { jsPDF } from 'jspdf';

export const generateCaseFile = (data) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(220, 53, 69); // Red for urgency
  doc.text('START // CYBER CRIME & DEEPFAKE REPORT', margin, 30);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Case ID: ${data.id}`, margin, 40);
  doc.text(`Generated: ${new Date(data.timestamp).toLocaleString()}`, margin, 45);
  doc.text(`Status: PENDING INVESTIGATION`, margin, 50);

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, 55, pageWidth - margin, 55);

  // Incident Details
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('Incident Details', margin, 70);
  
  doc.setFontSize(12);
  doc.text(`Offender Username: ${data.offender}`, margin, 80);
  doc.text(`Platform: ${data.platform}`, margin, 90);
  
  // Statement
  if (data.statement) {
    doc.text('Victim Statement:', margin, 110);
    doc.setFontSize(10);
    const splitText = doc.splitTextToSize(data.statement, pageWidth - (margin * 2));
    doc.text(splitText, margin, 120);
  }

  // Evidence Images
  let yPos = data.statement ? 150 : 110;
  
  const addImageToDoc = (imgData, label) => {
    if (!imgData) return;
    
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 30;
    }
    
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(label, margin, yPos);
    yPos += 10;
    
    // Add image with auto-detected format
    try {
      // Extract format from data URL (e.g., "data:image/png;base64,...")
      const format = imgData.match(/^data:image\/(\w+);base64,/)?.[1]?.toUpperCase() || 'JPEG';
      // jsPDF supports 'PNG', 'JPEG', 'WEBP' (in some versions), 'BMP'. 
      // Ensure specific formats are passed correctly.
      const validFormat = ['PNG', 'JPEG', 'JPG', 'WEBP'].includes(format) ? format : 'JPEG';

      // Keep aspect ratio roughly (simplified: fit within 100x100 box)
      const imgProps = doc.getImageProperties(imgData);
      const pdfWidth = 100;
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      doc.addImage(imgData, validFormat, margin, yPos, pdfWidth, pdfHeight); 
      yPos += pdfHeight + 10; 
    } catch (e) {
      console.error("PDF Image Error:", e);
      doc.setTextColor(255, 0, 0);
      doc.text('[Error loading image. Please ensure it is a valid JPG/PNG]', margin, yPos);
      yPos += 10;
    }
  };

  addImageToDoc(data.screenshotImage, 'Evidence 1: Offender Message/Post');
  addImageToDoc(data.deepfakeImage, 'Evidence 2: Deepfake Image');

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Generated by Deepfake Guardian`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save(`Case_${data.id}_Report.pdf`);
};

export const generateLegalNoticePDF = (data) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFontSize(16);
  doc.text('LEGAL NOTICE / CEASE AND DESIST', margin, 20);
  
  doc.setFontSize(12);
  doc.text(`To: ${data.offender}`, margin, 40);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, 50);
  
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Subject: Immediate Demand to Cease and Desist Deepfake Distribution', margin, 70);
  
  doc.setFont(undefined, 'normal');
  doc.setFontSize(11);
  const bodyText = `
This notice serves as a formal warning regarding the unauthorized creation and distribution of manipulated content (deepfakes) featuring my likeness on ${data.platform}.

Your actions constitute a violation of my privacy and personality rights, and may violate cybercrime laws applicable in your jurisdiction.

DEMAND:
1. Immediately remove the offending content from all platforms.
2. Cease any further distribution.
3. Confirm in writing that you have complied with these demands within 24 hours.

Failure to comply will result in immediate legal action, including but not limited to filing a First Information Report (FIR) with the Cyber Crime Cell.
  `;
  
  const splitBody = doc.splitTextToSize(bodyText.trim(), pageWidth - (margin * 2));
  doc.text(splitBody, margin, 90);
  
  doc.text('Sincerely,', margin, 200);
  doc.text('Victim / Legal Representative', margin, 210);

  doc.save(`Legal_Notice_${data.id}.pdf`);
};
